### ISSUE TITLE
 how to  upload external notebook  to IPFS?

### ISSUE THREAD

**Issue by linhanxiao** [pollinations/pollinations#337]
how to  upload external notebook  to IPFS? @voodoohop

**Comment by voodoohop** [comment]
Hi!

We need to create a document detailing how to do this. But actually I was planning to allow just passing a github URL of any notebook to Pollinations.

Do you have a specific one you would like to add to our public models? I can give a hand for now because it's not well documented.

If you use discord we could talk there. My username is: thomash#6943
