### ISSUE TITLE
Sharing URL's are too long.

### ISSUE THREAD

**Issue by gokaykucuk** [pollinations/pollinations#47]
The result pages have too long and cryptic URLs.

We can create a simple url shortener with a short domain name with serverless, so we can let users use a more user-friendly URL.

```ex,

https://pollinations.ai/p/Qmf3RViTYAoSfFpqtzADUKettXaXvCjnnw77dHoAAuEKCm -> plns.ai/3TgfR or pollinations.ai/3TgfR
```

We can still use the current domain and add the redirection service to the domain.

We might also let users "name" their creations, giving them a custom URL under the chosen domain. 
This naming can also be used to "pin" only named creations on our IPFS node which might filter out most of the noise. 

```ex, 

plns.ai/DreamyMorning

```

It can even be a really cheap but paid feature, something like few dollars per year. Or maybe this can kick in after a certain number of (ex. 3) custom names are created, we can ask for something like 1$/ per 1000 for custom names. 

Also even if the short URLs are sold, this feature should be not secured. If someone doesn't want to pay, they should just be able to clear cookies/reset browser cache/delete localStorage etc to get another 10 free url's.

This entire setup can be also done with NFT's as owners of these urls.

**Comment by voodoohop** [comment]
In my opinion this is another "luxury" feature. I'd still like to nail the stability and simplicity of the code before putting effort into making it more user-friendly. 

People are typing URLs less and less I would say.  If pollinations gets popular it will be more because of ease of use and good social media integration than the look of the URL. Web apps such as Gmail, docs, etc all work with quite long cryptic hashes in the URL I think.

We need to keep some database that maps strings to hashes which takes away directly from the decentralized aspect.

**Comment by gokaykucuk** [comment]
Makes sense, let's get the core fully functional and stable first!

**Comment by voodoohop** [comment]
Yeah I think as I mentioned in the chat we could start by making the notebook URLs friendly and then keep the sharing URLs as hashes. It feels a bit like a separate URL shortening service. We could use another domain for it to separate the responsibilities. A few services do it like that like goo.gl, ...

I think we also have some lower-hanging fruits such as more friendly social media posts and an easy interface for sharing on your own channels. #7

**Comment by voodoohop** [comment]
Possible url format for models before running them: https://pollinations.ai/p/Text-to-Image/CLIP-Guided_VQGAN
