### ISSUE TITLE
Fade in changes with new render over old image

### ISSUE THREAD

**Issue by jacksongoode** [pollinations/pollinations#83]
For more polish, it would be nice (and easy I believe) to add a fade in when a new render of the current state appears. The fade in could be done in css and could have a duration dependent on the previous/average time it takes for a new image to be added.

**Comment by voodoohop** [comment]
I would wait with these kinds of beauty features until the whole project is a little more advanced. there is some core functionality we still need to implement.

the idea is that you can do a lot more than just text-to-image with pollinations. that's why I would wait with these kinds of features as they are very specific to notebooks with image results.

not that we don't want to implement it in the future.
